EXTRACFLAGS = 
EXTRA_LIBS =

MODULE = run
SRCS = $(wildcard *.cpp)

OBJS = $(SRCS:.cpp=.o)

include ../../Makefile.defs

CFLAGS += -O2
#CFLAGS += -DFORSYDE_INTROSPECTION
#CFLAGS += -DFORSYDE_SELF_REPORTING
